### ISSUE TITLE
AttachmentExtension pool full.

### ISSUE THREAD

**Issue by Swompen** [Force-Developing/force-sling#1] opened 2024-12-15 21:49 UTC
**Describe the bug**
After i added this script to my server i've had a lot of player crashes. Most with:

![image](https://github.com/user-attachments/assets/79f1fb3d-4310-4b09-a852-135e5db5aa75)

I've also noticed when players crash and disconnects a TON of props lands on the ground. So lets say they have a bat on them, 20+ bats lands on the floor when they crash.

**Comment by Force-Developing** [comment] 2024-12-16 11:11
Hi Swompen,

Thank you for taking the time to report this issue! I've investigated the problem and found the cause: WeaponObjects couldn't be attached properly to a ped, so I used an invisible object as a workaround. However, I forgot to remove that invisible object when the weapon gets dropped, which led to the issue you're experiencing. Weapons also deletes themselfs if they are detached from the player and gets respawned properly.

I've implemented a fix for this in the latest version of the code. If you'd like to review the changes, feel free to check out the latest version in the repository. I believe this should resolve the issue, but let me know if you encounter any further problems or have feedback!

Here’s a preview of the fix in action:
[Preview](https://gyazo.com/b97ab5157c41d32ad4415309ab6c2ba8)
[MaxAttached](https://gyazo.com/5868ec05cb4127a1a8b8e5f45a18b8ba)

Thank you again for your reporting the issue to improve the project!

**Closed as completed by Force-Developing** 2024-12-16 11:11 UTC
Labels: bug, enhancement, Resolved
